// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package db

import (
	"context"
)

const executionCreate = `-- name: ExecutionCreate :one
INSERT INTO executions (workflow_id, org_id, log_status, credits_spent)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_id, org_id, log_status, credits_spent, executed_at
`

type ExecutionCreateParams struct {
	WorkflowID   int64  `json:"workflow_id"`
	OrgID        int64  `json:"org_id"`
	LogStatus    string `json:"log_status"`
	CreditsSpent int32  `json:"credits_spent"`
}

func (q *Queries) ExecutionCreate(ctx context.Context, arg ExecutionCreateParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, executionCreate,
		arg.WorkflowID,
		arg.OrgID,
		arg.LogStatus,
		arg.CreditsSpent,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.LogStatus,
		&i.CreditsSpent,
		&i.ExecutedAt,
	)
	return i, err
}

const executionListByWorkflow = `-- name: ExecutionListByWorkflow :many
SELECT id, workflow_id, org_id, log_status, credits_spent, executed_at FROM executions WHERE workflow_id = $1 ORDER BY executed_at DESC
`

func (q *Queries) ExecutionListByWorkflow(ctx context.Context, workflowID int64) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, executionListByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.OrgID,
			&i.LogStatus,
			&i.CreditsSpent,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
