// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"
)

const organizationFindByID = `-- name: OrganizationFindByID :one
SELECT id, name, plan_type, credits_balance FROM organizations WHERE id = $1
`

func (q *Queries) OrganizationFindByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, organizationFindByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.CreditsBalance,
	)
	return i, err
}

const organizationUpdateCredits = `-- name: OrganizationUpdateCredits :exec
UPDATE organizations SET credits_balance = credits_balance + $2 WHERE id = $1
`

type OrganizationUpdateCreditsParams struct {
	ID             int64 `json:"id"`
	CreditsBalance int32 `json:"credits_balance"`
}

func (q *Queries) OrganizationUpdateCredits(ctx context.Context, arg OrganizationUpdateCreditsParams) error {
	_, err := q.db.ExecContext(ctx, organizationUpdateCredits, arg.ID, arg.CreditsBalance)
	return err
}
