package gluegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/geul-org/fullend/internal/statemachine"
)

// GenerateStateMachines generates Go state machine packages from stateDiagrams.
// Output: <artifactsDir>/backend/internal/states/<id>state/<id>state.go
func GenerateStateMachines(diagrams []*statemachine.StateDiagram, artifactsDir, modulePath string) error {
	if len(diagrams) == 0 {
		return nil
	}

	statesBaseDir := filepath.Join(artifactsDir, "backend", "internal", "states")

	for _, d := range diagrams {
		pkgName := d.ID + "state"
		pkgDir := filepath.Join(statesBaseDir, pkgName)
		if err := os.MkdirAll(pkgDir, 0755); err != nil {
			return fmt.Errorf("create states dir for %s: %w", d.ID, err)
		}

		src := generateStateMachineSource(d, pkgName)
		outPath := filepath.Join(pkgDir, pkgName+".go")
		if err := os.WriteFile(outPath, []byte(src), 0644); err != nil {
			return fmt.Errorf("write state machine %s: %w", d.ID, err)
		}
	}

	return nil
}

// generateStateMachineSource generates the Go source for a state machine package.
func generateStateMachineSource(d *statemachine.StateDiagram, pkgName string) string {
	var buf strings.Builder

	buf.WriteString(fmt.Sprintf("// Code generated by fullend gen — do not edit.\n"))
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	// State constants.
	states := make([]string, len(d.States))
	copy(states, d.States)
	sort.Strings(states)

	buf.WriteString("// State constants.\nconst (\n")
	for _, s := range states {
		constName := ucFirst(s)
		buf.WriteString(fmt.Sprintf("\tState%s = %q\n", constName, s))
	}
	buf.WriteString(")\n\n")

	// Determine the status field type from the diagram.
	fieldType := inferFieldType(d)

	// transitionKey type.
	buf.WriteString("type transitionKey struct {\n\tfrom  string\n\tevent string\n}\n\n")

	// Transitions map.
	buf.WriteString("var transitions = map[transitionKey]string{\n")
	for _, t := range d.Transitions {
		buf.WriteString(fmt.Sprintf("\t{%q, %q}: %q,\n", t.From, t.Event, t.To))
	}
	buf.WriteString("}\n\n")

	// CanTransition function — signature depends on field type.
	switch fieldType {
	case "bool":
		buf.WriteString(generateBoolCanTransition(d))
	default:
		// String-based status field.
		buf.WriteString(`// CanTransition checks if the given event is valid from the current state.
func CanTransition(status string, event string) bool {
	_, ok := transitions[transitionKey{from: status, event: event}]
	return ok
}
`)
	}

	return buf.String()
}

// generateBoolCanTransition generates CanTransition for boolean status fields.
func generateBoolCanTransition(d *statemachine.StateDiagram) string {
	// Find the mapping: which state name corresponds to true/false.
	// Convention: state name matching a common boolean pattern → true.
	// "published" → true, "unpublished" → false, etc.
	trueState, falseState := inferBoolStates(d)

	var buf strings.Builder
	buf.WriteString("// CanTransition checks if the given event is valid from the current state.\n")
	buf.WriteString("func CanTransition(fieldValue bool, event string) bool {\n")
	buf.WriteString("\tcurrent := stateFromBool(fieldValue)\n")
	buf.WriteString("\t_, ok := transitions[transitionKey{from: current, event: event}]\n")
	buf.WriteString("\treturn ok\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func stateFromBool(v bool) string {\n")
	buf.WriteString("\tif v {\n")
	buf.WriteString(fmt.Sprintf("\t\treturn %q\n", trueState))
	buf.WriteString("\t}\n")
	buf.WriteString(fmt.Sprintf("\treturn %q\n", falseState))
	buf.WriteString("}\n")

	return buf.String()
}

// inferFieldType determines if the status field is boolean or string-based.
// Heuristic: if exactly 2 live states (excluding terminal states like "deleted")
// and one has "un" prefix of the other, it's boolean.
func inferFieldType(d *statemachine.StateDiagram) string {
	// Collect non-terminal states (states that have outgoing transitions).
	hasOutgoing := make(map[string]bool)
	for _, t := range d.Transitions {
		hasOutgoing[t.From] = true
	}

	// If we can find a pair like published/unpublished, it's boolean.
	for _, s := range d.States {
		negated := "un" + s
		for _, s2 := range d.States {
			if s2 == negated {
				return "bool"
			}
		}
	}

	return "string"
}

// inferBoolStates returns (trueState, falseState) for boolean diagrams.
func inferBoolStates(d *statemachine.StateDiagram) (string, string) {
	for _, s := range d.States {
		negated := "un" + s
		for _, s2 := range d.States {
			if s2 == negated {
				return s, s2 // s = true, "un"+s = false
			}
		}
	}
	// Fallback: initial state = false.
	if d.InitialState != "" {
		for _, s := range d.States {
			if s != d.InitialState && s != "deleted" {
				return s, d.InitialState
			}
		}
	}
	return d.States[0], d.States[1]
}
