// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

package db

import (
	"context"
)

const executionLogCreate = `-- name: ExecutionLogCreate :one
INSERT INTO execution_logs (workflow_id, org_id, status)
VALUES ($1, $2, $3)
RETURNING id, workflow_id, org_id, status, credits_spent, executed_at
`

type ExecutionLogCreateParams struct {
	WorkflowID int64
	OrgID      int64
	Status     string
}

func (q *Queries) ExecutionLogCreate(ctx context.Context, arg ExecutionLogCreateParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, executionLogCreate, arg.WorkflowID, arg.OrgID, arg.Status)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ExecutedAt,
	)
	return i, err
}
