// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Action struct {
	ID              int64
	WorkflowID      int64
	ActionType      string
	PayloadTemplate string
	SequenceOrder   int32
}

type ExecutionLog struct {
	ID           int64
	WorkflowID   int64
	OrgID        int64
	Status       string
	CreditsSpent int32
	ExecutedAt   time.Time
}

type Organization struct {
	ID             int64
	Name           string
	PlanType       string
	CreditsBalance int32
}

type User struct {
	ID           int64
	OrgID        int64
	Email        string
	PasswordHash string
	Role         string
}

type Workflow struct {
	ID           int64
	OrgID        int64
	Title        string
	TriggerEvent string
	Status       string
	CreatedAt    time.Time
}
